/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DefaultRouteImport } from './routes/default'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AdminSubjectsIndexRouteImport } from './routes/admin/subjects/index'
import { Route as AdminSectionsIndexRouteImport } from './routes/admin/sections/index'
import { Route as AdminLessonsIndexRouteImport } from './routes/admin/lessons/index'
import { Route as AdminChaptersIndexRouteImport } from './routes/admin/chapters/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminSubjectsNewRouteImport } from './routes/admin/subjects/new'
import { Route as AdminSubjectsSubjectIdRouteImport } from './routes/admin/subjects/$subjectId'
import { Route as AdminSectionsNewRouteImport } from './routes/admin/sections/new'
import { Route as AdminSectionsSectionIdRouteImport } from './routes/admin/sections/$sectionId'
import { Route as AdminLessonsNewRouteImport } from './routes/admin/lessons/new'
import { Route as AdminLessonsLessonIdRouteImport } from './routes/admin/lessons/$lessonId'
import { Route as AdminChaptersNewRouteImport } from './routes/admin/chapters/new'
import { Route as AdminChaptersChapterIdRouteImport } from './routes/admin/chapters/$chapterId'

const DefaultRoute = DefaultRouteImport.update({
  id: '/default',
  path: '/default',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AdminSubjectsIndexRoute = AdminSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsIndexRoute = AdminSectionsIndexRouteImport.update({
  id: '/sections/',
  path: '/sections/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsIndexRoute = AdminLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChaptersIndexRoute = AdminChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubjectsNewRoute = AdminSubjectsNewRouteImport.update({
  id: '/subjects/new',
  path: '/subjects/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsSubjectIdRoute = AdminSubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsNewRoute = AdminSectionsNewRouteImport.update({
  id: '/sections/new',
  path: '/sections/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsSectionIdRoute = AdminSectionsSectionIdRouteImport.update({
  id: '/sections/$sectionId',
  path: '/sections/$sectionId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsNewRoute = AdminLessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsLessonIdRoute = AdminLessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChaptersNewRoute = AdminChaptersNewRouteImport.update({
  id: '/chapters/new',
  path: '/chapters/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChaptersChapterIdRoute = AdminChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/default': typeof DefaultRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/admin/chapters/$chapterId': typeof AdminChaptersChapterIdRoute
  '/admin/chapters/new': typeof AdminChaptersNewRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/lessons/new': typeof AdminLessonsNewRoute
  '/admin/sections/$sectionId': typeof AdminSectionsSectionIdRoute
  '/admin/sections/new': typeof AdminSectionsNewRoute
  '/admin/subjects/$subjectId': typeof AdminSubjectsSubjectIdRoute
  '/admin/subjects/new': typeof AdminSubjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/chapters': typeof AdminChaptersIndexRoute
  '/admin/lessons': typeof AdminLessonsIndexRoute
  '/admin/sections': typeof AdminSectionsIndexRoute
  '/admin/subjects': typeof AdminSubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/default': typeof DefaultRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/admin/chapters/$chapterId': typeof AdminChaptersChapterIdRoute
  '/admin/chapters/new': typeof AdminChaptersNewRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/lessons/new': typeof AdminLessonsNewRoute
  '/admin/sections/$sectionId': typeof AdminSectionsSectionIdRoute
  '/admin/sections/new': typeof AdminSectionsNewRoute
  '/admin/subjects/$subjectId': typeof AdminSubjectsSubjectIdRoute
  '/admin/subjects/new': typeof AdminSubjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/chapters': typeof AdminChaptersIndexRoute
  '/admin/lessons': typeof AdminLessonsIndexRoute
  '/admin/sections': typeof AdminSectionsIndexRoute
  '/admin/subjects': typeof AdminSubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/default': typeof DefaultRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/admin/chapters/$chapterId': typeof AdminChaptersChapterIdRoute
  '/admin/chapters/new': typeof AdminChaptersNewRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/lessons/new': typeof AdminLessonsNewRoute
  '/admin/sections/$sectionId': typeof AdminSectionsSectionIdRoute
  '/admin/sections/new': typeof AdminSectionsNewRoute
  '/admin/subjects/$subjectId': typeof AdminSubjectsSubjectIdRoute
  '/admin/subjects/new': typeof AdminSubjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/chapters/': typeof AdminChaptersIndexRoute
  '/admin/lessons/': typeof AdminLessonsIndexRoute
  '/admin/sections/': typeof AdminSectionsIndexRoute
  '/admin/subjects/': typeof AdminSubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/default'
    | '/dashboard'
    | '/settings'
    | '/admin/'
    | '/sign-in'
    | '/sign-up'
    | '/admin/chapters/$chapterId'
    | '/admin/chapters/new'
    | '/admin/lessons/$lessonId'
    | '/admin/lessons/new'
    | '/admin/sections/$sectionId'
    | '/admin/sections/new'
    | '/admin/subjects/$subjectId'
    | '/admin/subjects/new'
    | '/api/auth/$'
    | '/admin/chapters'
    | '/admin/lessons'
    | '/admin/sections'
    | '/admin/subjects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/default'
    | '/dashboard'
    | '/settings'
    | '/admin'
    | '/sign-in'
    | '/sign-up'
    | '/admin/chapters/$chapterId'
    | '/admin/chapters/new'
    | '/admin/lessons/$lessonId'
    | '/admin/lessons/new'
    | '/admin/sections/$sectionId'
    | '/admin/sections/new'
    | '/admin/subjects/$subjectId'
    | '/admin/subjects/new'
    | '/api/auth/$'
    | '/admin/chapters'
    | '/admin/lessons'
    | '/admin/sections'
    | '/admin/subjects'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin'
    | '/default'
    | '/_auth/dashboard'
    | '/_auth/settings'
    | '/admin/'
    | '/sign-in/'
    | '/sign-up/'
    | '/admin/chapters/$chapterId'
    | '/admin/chapters/new'
    | '/admin/lessons/$lessonId'
    | '/admin/lessons/new'
    | '/admin/sections/$sectionId'
    | '/admin/sections/new'
    | '/admin/subjects/$subjectId'
    | '/admin/subjects/new'
    | '/api/auth/$'
    | '/admin/chapters/'
    | '/admin/lessons/'
    | '/admin/sections/'
    | '/admin/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DefaultRoute: typeof DefaultRoute
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/default': {
      id: '/default'
      path: '/default'
      fullPath: '/default'
      preLoaderRoute: typeof DefaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/subjects/': {
      id: '/admin/subjects/'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections/': {
      id: '/admin/sections/'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons/': {
      id: '/admin/lessons/'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chapters/': {
      id: '/admin/chapters/'
      path: '/chapters'
      fullPath: '/admin/chapters'
      preLoaderRoute: typeof AdminChaptersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subjects/new': {
      id: '/admin/subjects/new'
      path: '/subjects/new'
      fullPath: '/admin/subjects/new'
      preLoaderRoute: typeof AdminSubjectsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects/$subjectId': {
      id: '/admin/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/admin/subjects/$subjectId'
      preLoaderRoute: typeof AdminSubjectsSubjectIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections/new': {
      id: '/admin/sections/new'
      path: '/sections/new'
      fullPath: '/admin/sections/new'
      preLoaderRoute: typeof AdminSectionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections/$sectionId': {
      id: '/admin/sections/$sectionId'
      path: '/sections/$sectionId'
      fullPath: '/admin/sections/$sectionId'
      preLoaderRoute: typeof AdminSectionsSectionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons/new': {
      id: '/admin/lessons/new'
      path: '/lessons/new'
      fullPath: '/admin/lessons/new'
      preLoaderRoute: typeof AdminLessonsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons/$lessonId': {
      id: '/admin/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/admin/lessons/$lessonId'
      preLoaderRoute: typeof AdminLessonsLessonIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chapters/new': {
      id: '/admin/chapters/new'
      path: '/chapters/new'
      fullPath: '/admin/chapters/new'
      preLoaderRoute: typeof AdminChaptersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chapters/$chapterId': {
      id: '/admin/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/admin/chapters/$chapterId'
      preLoaderRoute: typeof AdminChaptersChapterIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthSettingsRoute: AuthSettingsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminChaptersChapterIdRoute: typeof AdminChaptersChapterIdRoute
  AdminChaptersNewRoute: typeof AdminChaptersNewRoute
  AdminLessonsLessonIdRoute: typeof AdminLessonsLessonIdRoute
  AdminLessonsNewRoute: typeof AdminLessonsNewRoute
  AdminSectionsSectionIdRoute: typeof AdminSectionsSectionIdRoute
  AdminSectionsNewRoute: typeof AdminSectionsNewRoute
  AdminSubjectsSubjectIdRoute: typeof AdminSubjectsSubjectIdRoute
  AdminSubjectsNewRoute: typeof AdminSubjectsNewRoute
  AdminChaptersIndexRoute: typeof AdminChaptersIndexRoute
  AdminLessonsIndexRoute: typeof AdminLessonsIndexRoute
  AdminSectionsIndexRoute: typeof AdminSectionsIndexRoute
  AdminSubjectsIndexRoute: typeof AdminSubjectsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminChaptersChapterIdRoute: AdminChaptersChapterIdRoute,
  AdminChaptersNewRoute: AdminChaptersNewRoute,
  AdminLessonsLessonIdRoute: AdminLessonsLessonIdRoute,
  AdminLessonsNewRoute: AdminLessonsNewRoute,
  AdminSectionsSectionIdRoute: AdminSectionsSectionIdRoute,
  AdminSectionsNewRoute: AdminSectionsNewRoute,
  AdminSubjectsSubjectIdRoute: AdminSubjectsSubjectIdRoute,
  AdminSubjectsNewRoute: AdminSubjectsNewRoute,
  AdminChaptersIndexRoute: AdminChaptersIndexRoute,
  AdminLessonsIndexRoute: AdminLessonsIndexRoute,
  AdminSectionsIndexRoute: AdminSectionsIndexRoute,
  AdminSubjectsIndexRoute: AdminSubjectsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DefaultRoute: DefaultRoute,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
